# fly.toml app configuration file generated for librechat-52ai-icu on 2024-07-06T22:24:19+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'librechat-52ai-icu'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
